name: beacon_flutter
description: The Beacon Flutter Plugin provides Flutter developers with tools useful for setting up communication between native wallets supporting Tezos and dApps that implement beacon-sdk.
version: 0.0.4
homepage: https://github.com/TalaoDAO/beacon

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  base_codecs: ^1.0.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:  
  plugin:
    platforms:
      android:
        package: io.altme.beacon.beacon
        pluginClass: BeaconPlugin
      ios:
        pluginClass: BeaconPlugin
