name: beacon_flutter
description: A new Flutter beacon plugin.
version: 0.0.1
homepage: https://github.com/TalaoDAO/beacon

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 

flutter:  
  plugin:
    platforms:
      android:
        package: io.altme.beacon.beacon
        pluginClass: BeaconPlugin
      ios:
        pluginClass: BeaconPlugin
